service: news-api-server
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: ap-northeast-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
          cors: true
  news_trends:
    handler: services.news_trends.main
    events:
      - http:
          path: /news_trends
          method: get
          cors: true